# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
<<<<<<< HEAD
    branches:
      - main

  pull_request:
    branches:
      - main
=======
    branches: [master]
  pull_request:
    branches: [master]
>>>>>>> 9c47762d29682a3f3227af2c8d47d3b0937c8775

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
<<<<<<< HEAD
    runs-on: ubuntu-latest
=======
    runs-on: windows-latest
>>>>>>> 9c47762d29682a3f3227af2c8d47d3b0937c8775

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
<<<<<<< HEAD
          node-version: "16.x"
=======
          node-version: "14"
>>>>>>> 9c47762d29682a3f3227af2c8d47d3b0937c8775
          check-latest: true
      - run: npm install
      - run: npm run build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
<<<<<<< HEAD
          AWS_REGION: "us-east-1" # optional: defaults to us-east-1
=======
          AWS_REGION: "<YOUR-REGION>" # optional: defaults to us-east-1
>>>>>>> 9c47762d29682a3f3227af2c8d47d3b0937c8775
          SOURCE_DIR: "build" # optional: defaults to entire repository
